spring:
    application:
        name: students
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/votes
        username: postgres
        password: 55164937
    jpa:
      hibernate:
        ddl-auto: update
server:
    port: 8080