spring:
    application:
        name: students
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/*******
        username: *******
        password: *******
    jpa:
      hibernate:
        ddl-auto: update
server:
    port: 8080